name: Manage lifecycle Helm Release Cleaner

env:
  USER: devopsiaci
  REPO: helm-release-cleaner

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build Helm Release Cleaner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        id: semantic
        with:
          branches: |
            [
              'main'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        if: ${{ steps.semantic.outputs.new_release_published == 'true' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        if: ${{ steps.semantic.outputs.new_release_published == 'true' }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        env:
          VERSION: ${{ steps.semantic.outputs.new_release_version }}
        with:
          context: .
          push: true
          tags: |
            ${{ env.USER }}/${{ env.REPO }}:${{ env.VERSION }}
            ${{ env.USER }}/${{ env.REPO }}:latest

      - name: Update Docker registry description
        if: ${{ steps.semantic.outputs.new_release_published == 'true' }}
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.USER }}/${{ env.REPO }}
